// Generated by Wrangler by running `wrangler types`

interface Env {
	PUBLIC_JWK_CACHE_KV: KVNamespace;
	FIREBASE_AUTH_EMULATOR_HOST: "127.0.0.1:9099";
	PROJECT_ID: "fitness-app";
	PUBLIC_JWK_CACHE_KEY: "public-jwk-cache-key";
	SERVICE_ACCOUNT_JSON: string;
	TRUSTED_ENV_SECRET: string;
	FITNESS_APP_GRAPHQL: Fetcher;
}
